import { Link } from "wouter";
import { ArrowRight, Bot, CirclePlus, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";

const statusTone: Record<string, string> = { WAITING_APPROVAL: "bg-amber-400/15 text-amber-200 border-amber-400/30", COMPLETED: "bg-emerald-400/15 text-emerald-200 border-emerald-400/30", REJECTED: "bg-slate-400/15 text-slate-200 border-slate-400/30", FAILED: "bg-rose-400/15 text-rose-200 border-rose-400/30" };

export default function MissionDashboard() {
  const missions = trpc.missions.list.useQuery();
  const launch = trpc.missions.launchFixture.useMutation({ onSuccess: () => missions.refetch() });
  const pending = missions.data?.filter(item => item?.mission.status === "WAITING_APPROVAL").length ?? 0;
  return <div className="forge-page space-y-8">
    <section className="hero-grid rounded-[28px] border border-white/10 px-7 py-8 md:px-10 md:py-10"><div className="max-w-2xl"><p className="eyebrow">Approval-gated incident response</p><h1 className="mt-4 text-4xl font-semibold tracking-[-0.045em] text-white md:text-6xl">Engineering missions, <span className="text-amber-300">under control.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-300">Investigate a bounded failure, verify the smallest safe repair, and require an explicit decision before the system records any external action.</p><div className="mt-8 flex flex-wrap gap-3"><Button className="h-11 rounded-xl bg-amber-300 px-5 text-slate-950 hover:bg-amber-200" onClick={() => launch.mutate()} disabled={launch.isPending}><CirclePlus className="mr-2 h-4 w-4" /> {launch.isPending ? "Starting mission…" : "Run deterministic fixture"}</Button><Link href="/readiness" className="inline-flex h-11 items-center rounded-xl border border-white/15 bg-white/5 px-4 text-sm font-medium text-white transition-colors hover:bg-white/10">Integration readiness <ArrowRight className="ml-2 h-4 w-4" /></Link></div>{launch.error ? <p className="mt-3 text-sm text-rose-300">{launch.error.message}</p> : null}</div><div className="hero-orbit mt-8 md:mt-0"><div className="orb-core"><ShieldCheck className="h-10 w-10" /></div><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="orbit-label label-a">VERIFY</div><div className="orbit-label label-b">APPROVE</div><div className="orbit-label label-c">ACT</div></div></section>
    <section className="grid gap-4 md:grid-cols-3"><Metric label="Mission ledger" value={`${missions.data?.length ?? 0}`} detail="Persisted incident records" /><Metric label="Human review" value={`${pending}`} detail="Waiting for a decision" accent="amber" /><Metric label="Action policy" value="0 live" detail="External actions stay simulated" accent="green" /></section>
    <section className="rounded-[24px] border border-white/10 bg-slate-950/60 p-5 shadow-2xl shadow-black/20 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Mission dashboard</p><h2 className="mt-2 text-2xl font-semibold text-white">Current engineering missions</h2></div><div className="flex items-center gap-2 text-sm text-slate-400"><Bot className="h-4 w-4 text-amber-300" /> Deterministic fixture adapter</div></div><div className="mt-6 overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-[1.3fr_.9fr_.7fr_.6fr] gap-3 bg-white/[0.04] px-4 py-3 text-[11px] font-semibold uppercase tracking-[0.14em] text-slate-400 md:px-5"><span>Mission</span><span>Repository</span><span>Status</span><span className="text-right">Last activity</span></div>{missions.isLoading ? <div className="px-5 py-12 text-sm text-slate-400">Loading persisted missions…</div> : null}{!missions.isLoading && !missions.data?.length ? <div className="px-5 py-12 text-sm text-slate-400">No mission exists yet. Run the deterministic fixture to create a persisted incident workflow.</div> : null}{missions.data?.map(bundle => bundle ? <Link key={bundle.mission.id} href={`/missions/${bundle.mission.id}`} className="grid grid-cols-[1.3fr_.9fr_.7fr_.6fr] gap-3 border-t border-white/[0.07] px-4 py-4 transition-colors hover:bg-white/[0.035] md:px-5"><span><strong className="block text-sm text-white">{bundle.mission.title}</strong><span className="mt-1 block text-xs text-slate-500">{bundle.mission.id}</span></span><span className="truncate text-sm text-slate-300">{bundle.mission.repository}</span><span><Badge className={`border text-[10px] ${statusTone[bundle.mission.status] ?? "bg-sky-400/15 text-sky-200 border-sky-400/30"}`}>{bundle.mission.status.replace("_", " ")}</Badge></span><span className="text-right text-xs text-slate-400">{new Date(bundle.mission.updatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></Link> : null)}</div></section>
  </div>;
}
function Metric({ label, value, detail, accent }: { label: string; value: string; detail: string; accent?: "amber" | "green" }) { const accentClass = accent === "amber" ? "text-amber-300" : accent === "green" ? "text-emerald-300" : "text-white"; return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><p className="text-xs font-medium uppercase tracking-[0.13em] text-slate-500">{label}</p><p className={`mt-3 text-3xl font-semibold tracking-tight ${accentClass}`}>{value}</p><p className="mt-2 text-sm text-slate-400">{detail}</p></div>; }
